title: "Anthony Rizkallah"
theme: jekyll-theme-minimal
remote_theme: jekyll/minima
header_pages: []
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
include:
  - assets/style.css
